export const cateringIcon = <i className="fa-solid fa-utensils"></i>
export const museumIcon = <i className="fa-solid fa-building-columns"></i>
export const accomidationIcon = <i className="fa-solid fa-bed"></i>
export const commercialIcon = <i className="fa-solid fa-store"></i>
export const entertainmentIcon = <i className="fa-solid fa-masks-theater"></i>
export const naturalIcon = <i className="fa-solid fa-tree"></i>
export const tourismIcon = <i className="fa-solid fa-van-shuttle"></i>
export const placeIcon = <i className="fa-solid fa-location-dot"></i>
export const chevronDown = <i className="fa-solid fa-circle-chevron-down"></i>
export const chevronUp = <i className="fa-solid fa-circle-chevron-up"></i>
export const searchIcon = <i className="fa-solid fa-magnifying-glass"></i>
export const spaIcon = <i className="fa-solid fa-spa"></i>
export const imageIcon = <i className="fa-solid fa-images"></i>